baseURL = 'https://fsdad.com/'
languageCode = 'en-us'
title = 'FSD Ad'

theme = "fsdad"

[menus]
  [[menus.main]]
    name = 'Clips'
    pageRef = '/clips'
    weight = 25

  [[menus.main]]
    name = 'Submit'
    url = 'https://submit.fsdad.com'
    weight = 50

  [[menus.main]]
    name = 'Source code'
    url = 'https://github.com/namnd/fsdad.com'
    weight = 100

[build]
  [build.buildStats]
    enable = true
  [[build.cachebusters]]
    source = 'assets/notwatching/hugo_stats\.json'
    target = 'css'
  [[build.cachebusters]]
    source = '(postcss|tailwind)\.config\.js'
    target = 'css'
[module]
  [[module.mounts]]
    source = 'assets'
    target = 'assets'
  [[module.mounts]]
    disableWatch = true
    source = 'hugo_stats.json'
    target = 'assets/notwatching/hugo_stats.json'
